CREATE TABLE scheduler_run (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name         VARCHAR(100)             NOT NULL,
    started_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at      TIMESTAMP WITH TIME ZONE,
    items_processed  INT                      NOT NULL DEFAULT 0,
    status           VARCHAR(10)              NOT NULL CHECK (status IN ('OK', 'FAIL')),
    error_message    VARCHAR(2000)
);

CREATE INDEX idx_scheduler_run_job_finished ON scheduler_run(job_name, finished_at DESC);
