CREATE TABLE notification (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sent_date  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message    VARCHAR(2000)             NOT NULL,
    type       VARCHAR(50)      NOT NULL DEFAULT 'GENERAL'
        CHECK (type IN ('DUE_REMINDER', 'OVERDUE_ALERT', 'RESERVATION_READY', 'GENERAL')),
    loan_id    INT,
    user_id    INT              NOT NULL,
    status     VARCHAR(50)      NOT NULL DEFAULT 'NOT_ACKNOWLEDGED'
        CHECK (status IN ('ACKNOWLEDGED', 'NOT_ACKNOWLEDGED')),
    CONSTRAINT fk_notification_loan
        FOREIGN KEY (loan_id) REFERENCES loan(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_notification_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_notification_loan ON notification(loan_id);
CREATE INDEX idx_notification_user ON notification(user_id);
