spring.application.name=ulms

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/ulms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:db_password}

# Flyway
spring.flyway.clean-disabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
