spring.application.name=ulms

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/usml_db
spring.datasource.username=postgres
spring.datasource.password=pass123

# Flyway
spring.flyway.clean-disabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
